### ISSUE TITLE
Show current selected profiles

### ISSUE THREAD

**Issue by chargerdude70** [FlightOne/RaceFlightOne#104]
When changing options in the drop downs (eg. QUICK CHANGE FILTER LEVELS) of "any" of the the GUI tabs, could it please "STAY" highlighted even after that tab is left? After a choice is made and you leave that tab, then get back into it, you have no clue what setting you are at. The "Highlighted" area always defaults to the "top" selection

**Comment by Arti3DPlayer** [comment]
@rs2k i need some variable for current selected pid or rate profile, to implement this feature

**Comment by Arti3DPlayer** [comment]
This been added in 1.1.140
