### ISSUE TITLE
Configurator 572 bug _ not saving CONFIGURATION TAB

### ISSUE THREAD

**Issue by snailfpv** [FlightOne/RaceFlightOne#263]
In the version 572 of x64 GUI it won't save variables. Whne trying to change TAB (to i.e. PID) it gives a prompt to save and continue but nothing happens after clicking that. In 571 (x64) it works fine and saves all the variables which 572 can read but still not save.

**Comment by Arti3DPlayer** [comment]
solved in 0.572.1
