### ISSUE TITLE
Bolt V2 + Millivolt OSD

### ISSUE THREAD

**Issue by MReFPV** [FlightOne/RaceFlightOne#264]
Hi, 

Bolt V2 Connected to Millivolt OSD FC (Raceflight 571) does not show correct Current Reading.

14 Ampere with no Lipo connected, 70A with Lipo Connected, but does not change on arming the Kwad.
Millivolt is set to BLheliS with Current Sensor (Solder Jumper).

![image](https://user-images.githubusercontent.com/37596658/37680106-3439ca38-2c83-11e8-9d85-8fee6d3b035c.png)

![image](https://user-images.githubusercontent.com/37596658/37680149-563eb21a-2c83-11e8-8d15-2aecc87b63a1.png)

![image](https://user-images.githubusercontent.com/37596658/37680246-9f07c36a-2c83-11e8-858e-06e8b6db87ee.png)
![image](https://user-images.githubusercontent.com/37596658/37680275-b0ec9f38-2c83-11e8-9ef9-c2594f08ef21.png)

Thanks

**Comment by PGIII** [comment]
are you using 6s ? is correct on 4s ?

**Comment by MReFPV** [comment]
4s is also not working, 11A with no lipo connected and 51A with lipo
connected.

51A (4s) 70A (6s) both values does not Change armed or disarmed Shows same
values.

PGIII <notifications@github.com> schrieb am Di., 20. März 2018, 21:22:

**Comment by MReFPV** [comment]
Tested Latest Flight One, still not working! Instead of current reading i
get a timer, if the Kwad is armed, it begins to count. Just Tested
betaflight on millivolt osd and guess what? It works! Too Bad raceflight
Hardware does not working with the Software it was made for 👎

siXsiXOneFPV <markusreit@googlemail.com> schrieb am Di., 20. März 2018,
22:43:

**Comment by fsy78** [comment]
Same here!!! Very disappointing!  Thought such things were tested before selling.

**Comment by PGIII** [comment]
it looks like the diagram for the current jumper may be backwards on the site, try reversing it, ive tested on my millivolt osd and everything is working, i found a bug that was causing current not to display properly, 577 will have the bug fixed and should be on the site shortly
