### ISSUE TITLE
Units of "mah" in OSD should be "mAh" not Amps and recommend dropping decimal

### ISSUE THREAD

**Issue by jake09mid** [FlightOne/RaceFlightOne#266]
The units of the numeric "mah" should be "mAh" in the OSD instead of A for amps. I also recommend dropping the decimal place because nobody needs that level of accuracy when you're counting to around 800-900ish on a 1300 mAh battery.

**Comment by antoineva33** [comment]
+1

**Comment by PGIII** [comment]
fixed in latest alpha
