### ISSUE TITLE
does not take of after switching back from a d shot command(590)

### ISSUE THREAD

**Issue by holmsiefpv** [FlightOne/RaceFlightOne#275]
I have just built a quad with the revolt osd and upgraded the firmware 590 cos there was a camera control bug in the one before. now when i crash and do turtle mode or motor beep and witches back to multi shot after d shot, first of all a random motor starts the start arming late and then when i arm it just vibrates into the air without me knowing. presides that the revolt flies great before a do that. please help and fix, thanks

**Comment by PGIII** [comment]
should be fixed in 592
