### ISSUE TITLE
Acrolevel issues

### ISSUE THREAD

**Issue by tromax14** [FlightOne/RaceFlightOne#278]
Hi.
I try to find a reponse on discord but I haven't.

I make a video from the issues : 
https://www.youtube.com/watch?v=gXwbgUinYvM

The quad was very stable in levelmode but when am switching in acrolevel it start shake.
I have the problem with firmware 575 so i change for 595 but same.

I found issues about this problem on github:
https://github.com/FlightOne/RaceFlightOne/issues/269

and I try with this setting : (with FW 595 )
set slp1=2.500
set sli1=0.050
set sla1=40.000
set sld1=0.014
save

but it same.

Hope you can help me !

Regards

**Comment by tromax14** [comment]
This setting don't help me (sorry) !
My dump without this modification : 

`#vr NAME:Flight One;VERSION:0.595.0.163 RC20;CONFIG:163
#fc HARDWARE:Flight One Revolt
#fl size=1799424
#fl total=16777216
#me modes active: 0
modes ARMED=8=70=100
modes LEVEL=6=-100=-70
modes ACROLEVEL=6=-29=30
modes FAILSAFE=0=0=0
modes LOGGING=0=0=0
modes BUZZER=7=70=100
modes LEDMODE=9=-29=30
modes LEDCOLOR=5=-29=30
modes DIRECT=0=0=0
modes VTXON=0=0=0
modes BRAINDRAIN=0=0=0
modes PROFILE2=0=0=0
modes PROFILE3=0=0=0
modes QUOPA=10=-29=30
modes PRELOAD=0=0=0
modes MOTORBEEP=7=70=100
modes AUTOKI=0=0=0
modes KILLSWITCH=0=0=0
modes VTXCHANNEL=0=0=0
modes OSDMENU=0=0=0
throttlecurve1 0=12=25=37=50=62=75=87=100
tpakp1 100=100=100=95=95=95=96=100=100
tpaki1 104=100=95=95=95=95=95=100=104
tpakd1 100=100=100=95=95=95=96=100=100
throttlecurve2 0=12=25=37=50=62=75=87=100
tpakp2 100=100=100=95=95=95=96=100=100
tpaki2 104=100=95=95=95=95=95=100=104
tpakd2 100=100=100=95=95=95=96=100=100
throttlecurve3 0=12=25=37=50=62=75=87=100
tpakp3 100=100=100=95=95=95=96=100=100
tpaki3 104=100=95=95=95=95=95=100=104
tpakd3 100=100=100=95=95=95=96=100=100
set mixer_type=0
set famx=100
set bounce_guard=0.000
set mixer_style=0
set esc_protocol=0
set m_dir=0
set esc_frequency=32000
set idle_percent=5.000
set idle_percent_inv=8.000
set spin_rec_str=750.000
set quopa_style=4
set esc_type=0
set mout1=3
set mout2=0
set mout3=1
set mout4=2
set mout5=4
set mout6=5
set mout7=6
set mout8=7
set led_count=8
set led_red=255
set led_green=0
set led_blue=0
set led_mode=6
set led_with_usb=0
set telem_smartaudio=0
set telem_sport=14
set telem_spek=0
set telem_msp=0
set telem_rfosd=0
set telem_tramp=0
set telem_crsf=0
set kill_ch=47
set vtx_ch=39
set vtx_power=0
set telem_mavlink=0
set adc_current_factor=42.000
set voffset=1.000
set vtx_pitmode_type=0
set vbat_buzzer=1
set vbat_cutoff=3.799
set bat_size=1300
set crsf_otx_cur_hack=1
set gyro_rotation=6
set board_calibrated=1
set man_gy_roll_angle=0.000
set man_gy_pitch_angle=0.000
set man_gy_yaw_angle=0.000
set wiz_trkr=63
set rf_loop_ctrl=20
set craft_name=Racer108537774
set pilot_name=RacePilot
set pname1=Profile1
set row1=0
set row2=0
set row3=0
set row4=0
set row5=0
set row6=0
set row7=0
set row8=0
set row9=0
set row10=0
set row11=0
set row12=0
set row13=0
set stick_curve1=4
set nsmoothing1=0
set rc_smoothing1=1.320
set pitch_rate1=400.000
set roll_rate1=400.000
set yaw_rate1=400.000
set pitch_acrop1=140.000
set roll_acrop1=140.000
set yaw_acrop1=140.000
set pitch_expo1=50.000
set roll_expo1=50.000
set yaw_expo1=50.000
set yaw_wc1=0
set roll_wc1=0
set pitch_wc1=0
set yaw_kp1=43.000
set roll_kp1=31.000
set pitch_kp1=31.000
set yaw_ki1=30.000
set roll_ki1=30.000
set pitch_ki1=30.000
set yaw_kd1=33.000
set roll_kd1=33.000
set pitch_kd1=33.000
set kd_limit1=0.349
set ki_limit1=0.259
set slp1=2.500
set sli1=0.050
set sla1=40.000
set sld1=0.014
set res_redux1=0
set yaw_rap1=90.000
set roll_rap1=90.000
set pitch_rap1=90.000
set sm_filter1=3
set filter_type1=3
set yaw_quick1=60.000
set roll_quick1=45.000
set pitch_quick1=45.000
set yaw_kd_rap1=60.000
set roll_kd_rap1=60.000
set pitch_kd_rap1=60.000
set x_vector_quick1=2.000
set x_vector_rap1=25.000
set y_vector_quick1=2.000
set y_vector_rap1=25.000
set z_vector_quick1=2.000
set z_vector_rap1=25.000
set yaw_lp_cf1=70.000
set roll_lp_cf1=70.000
set pitch_lp_cf1=70.000
set yaw_lp_cf2=70.000
set roll_lp_cf2=70.000
set pitch_lp_cf2=70.000
set yaw_lp_cf3=70.000
set roll_lp_cf3=70.000
set pitch_lp_cf3=70.000
set tpa_kp_curve_type1=1
set tpa_ki_curve_type1=1
set tpa_kd_curve_type1=1
set pname2=Profile2
set stick_curve2=4
set nsmoothing2=0
set rc_smoothing2=1.320
set pitch_rate2=400.000
set roll_rate2=400.000
set yaw_rate2=400.000
set pitch_acrop2=140.000
set roll_acrop2=140.000
set yaw_acrop2=140.000
set pitch_expo2=50.000
set roll_expo2=50.000
set yaw_expo2=50.000
set yaw_wc2=0
set roll_wc2=0
set pitch_wc2=0
set yaw_kp2=43.000
set roll_kp2=31.000
set pitch_kp2=31.000
set yaw_ki2=30.000
set roll_ki2=30.000
set pitch_ki2=30.000
set yaw_kd2=33.000
set roll_kd2=33.000
set pitch_kd2=33.000
set kd_limit2=0.349
set ki_limit2=0.259
set slp2=2.500
set sli2=0.050
set sla2=40.000
set sld2=0.014
set res_redux2=0
set yaw_rap2=90.000
set roll_rap2=90.000
set pitch_rap2=90.000
set sm_filter2=3
set filter_type2=3
set yaw_quick2=60.000
set roll_quick2=45.000
set pitch_quick2=45.000
set yaw_kd_rap2=60.000
set roll_kd_rap2=60.000
set pitch_kd_rap2=60.000
set x_vector_quick2=2.000
set x_vector_rap2=25.000
set y_vector_quick2=2.000
set y_vector_rap2=25.000
set z_vector_quick2=2.000
set z_vector_rap2=25.000
set tpa_kp_curve_type2=1
set tpa_ki_curve_type2=1
set tpa_kd_curve_type2=1
set pname3=Profile3
set stick_curve3=4
set rc_smoothing3=1.320
set nsmoothing3=0
set pitch_rate3=400.000
set roll_rate3=400.000
set yaw_rate3=400.000
set pitch_acrop3=140.000
set roll_acrop3=140.000
set yaw_acrop3=140.000
set pitch_expo3=50.000
set roll_expo3=50.000
set yaw_expo3=50.000
set yaw_wc3=0
set roll_wc3=0
set pitch_wc3=0
set yaw_kp3=43.000
set roll_kp3=31.000
set pitch_kp3=31.000
set yaw_ki3=30.000
set roll_ki3=30.000
set pitch_ki3=30.000
set yaw_kd3=33.000
set roll_kd3=33.000
set pitch_kd3=33.000
set kd_limit3=0.349
set ki_limit3=0.259
set slp3=2.500
set sli3=0.050
set sla3=40.000
set sld3=0.014
set res_redux3=0
set yaw_rap3=90.000
set roll_rap3=90.000
set pitch_rap3=90.000
set sm_filter3=3
set filter_type3=3
set yaw_quick3=60.000
set roll_quick3=45.000
set pitch_quick3=45.000
set yaw_kd_rap3=60.000
set roll_kd_rap3=60.000
set pitch_kd_rap3=60.000
set x_vector_quick3=2.000
set x_vector_rap3=25.000
set y_vector_quick3=2.000
set y_vector_rap3=25.000
set z_vector_quick3=2.000
set z_vector_rap3=25.000
set tpa_kp_curve_type3=1
set tpa_ki_curve_type3=1
set tpa_kd_curve_type3=1
set rx_protocol=4
set rx_usart=0
set arm_method=1
set rx_inv_direction=0
set pitch_deadband=0.014
set roll_deadband=0.014
set yaw_deadband=0.014
set throttle_deadband=0.000
set aux1_deadband=0.000
set aux2_deadband=0.000
set aux3_deadband=0.000
set aux4_deadband=0.000
set pitch_midrc=988
set roll_midrc=992
set yaw_midrc=990
set throttle_midrc=991
set aux1_midrc=990
set aux2_midrc=990
set aux3_midrc=990
set aux4_midrc=990
set pitch_minrc=172
set roll_minrc=172
set yaw_minrc=172
set throttle_minrc=172
set aux1_minrc=172
set aux2_minrc=172
set aux3_minrc=172
set aux4_minrc=172
set pitch_maxrc=1811
set roll_maxrc=1811
set yaw_maxrc=1811
set throttle_maxrc=1811
set aux1_maxrc=1811
set aux2_maxrc=1811
set aux3_maxrc=1811
set aux4_maxrc=1811
set pitch_map=2
set roll_map=1
set yaw_map=3
set throttle_map=0
set aux1_map=4
set aux2_map=5
set aux3_map=6
set aux4_map=7
set aux5_map=8
set aux6_map=9
set aux7_map=10
set aux8_map=11
set aux9_map=12
set aux10_map=13
set aux11_map=14
set aux12_map=15
set rc_calibrated=1
set bind=0
set short_throw=1
`

**Comment by PGIII** [comment]
will have to look into it, closing this issue since this is already one open about acrolevel

**Comment by tromax14** [comment]
Hope you find a solution !
