### ISSUE TITLE
Configurator 1.127 Current Value unreadable when changing PIDS on Mac

### ISSUE THREAD

**Issue by 2dogrc** [FlightOne/RaceFlightOne#284]
When you change the a value in the PID tuning screen, the last value is not visible.  Here i changed the D value

<img width="1680" alt="screenshot 2018-06-09 09 57 42" src="https://user-images.githubusercontent.com/17340442/41192462-f38dfe7c-6bcb-11e8-89f6-64ea6cba3603.png">

**Comment by Arti3DPlayer** [comment]
I don't seed D value on your screen ? what value you tried to set ?

**Comment by Arti3DPlayer** [comment]
Will fix in next version. Thanks
