### ISSUE TITLE
Correction to Voltage readings in internal OSD

### ISSUE THREAD

**Issue by madeinnovember** [FlightOne/RaceFlightOne#288]
With internal OSD in RevoltOSD (FW 1.1.140.184) Voltage currently displayed as :
16.44V > 16.23V > 16.12V > **16.2V**
However in telemetry last number actually is 16.**0**2V.
So there is missing "0" between 16. and 2V. And it's a little bit confusing :)

**Comment by PGIII** [comment]
should be fixed in latest beta 1.1.157, its available on discord right now, should be pushed to /beta if all testing goes well
